name: Hello-World

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps: 
    - run: python hello-world.py
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifactory@v2
    
    
  
